version: '3'

services:
  db_servlet_currency_exhanger:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5440:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: